name: Bump version
on:
  push:
    branches:
      [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.3
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: release.*
          append_to_pre_release_tag: ''
          custom_tag: release-test
          
      - name: Create a GitHub release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: ${{ steps.tag_version.outputs.new_tag }}
          automatic_release_tag: ${{ steps.tag_version.outputs.new_tag }}
          prerelease: true
          files: ${{ steps.tag_version.outputs.changelog }}
